version: "3"
services:
  client:
    image: "santgt5/client-complex-pro"
    mem_limit: 128m
    hostname: client
  server:
    image: "santgt5/server-complex"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PG_USER
      - PG_HOST=$PG_HOST
      - PG_DATABASE=$PG_DATABASE
      - PG_PASSWORD=$PG_PASSWORD
      - PG_PORT=$PG_PORT
  worker:
    image: "santgt5/worker-complex"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "santgt5/nginx-complex"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"